### Metrics
GET http://localhost:8080/metrics


### Health
GET http://localhost:8080/healthz


### Analyze
GET http://localhost:8080/v1/net-intent/analyze?domain=de0mpg.launches.appsflyersdk.com.


### UrlScan
GET http://localhost:8080/v1/net-intent/urlscan?domain=html-load.com.


### RDAP
GET http://localhost:8080/v1/net-intent/rdap?domain=html-load.com
