### Metrics
GET http://localhost:8080/metrics


### Health
GET http://localhost:8080/healthz


### Analyze
GET http://localhost:8080/v1/net-intent/analyze?domain=securepubads.g.doubleclick.net.


### UrlScan
GET http://localhost:8080/v1/net-intent/urlscan?domain=securepubads.g.doubleclick.net.


### RDAP
GET http://localhost:8080/v1/net-intent/rdap?domain=html-load.com
